Feature/8
f-lab-edu/careers pull request #9
Opened 2021-04-15 17:28 UTC by phantom08266

프로필 편집기능

- 프로필 추가, 수정기능

2021-04-16 03:47 UTC, f-lab-dev commented on sql/ddl.sql
> +    primary key (id, name), -- Profile 테이블에서 foreign key로 사용하기 위해 name도 pk설정
이거는 굳이 이름도 걸어줄 필요가 있나요? 외래키로는 id만 걸어줘도 될 것 같은데요~

2021-04-16 03:47 UTC, f-lab-dev commented on src/main/java/com/dev/careers/controller/CuratorController.java
> +        Integer id = curatorService.login(loginParamter);
`curatorService.login` 메소드는 사용자가 입력한 아이디와 비밀번호로 유저의 정보를 불러오는 메소드인 것 같습니다. 그럼 이름도 `login`으로 짓기보단 `getUserIdByIdAndPassword` 같은 이름으로 지어주는게 낫지 않을까요?

2021-04-16 03:47 UTC, f-lab-dev commented on src/main/java/com/dev/careers/controller/ProfileController.java
> +@RequestMapping("profile")
여기는 복수형으로 지어주는게 좋아보입니다~

https://docs.microsoft.com/ko-kr/azure/architecture/best-practices/api-design

2021-04-16 03:47 UTC, f-lab-dev commented on src/main/java/com/dev/careers/controller/ProfileController.java
> +    @PostMapping("update")
update이므로 `PUT` 메소드로 하는게 낫지 않을까요?

2021-04-16 03:47 UTC, f-lab-dev commented on src/main/java/com/dev/careers/controller/ProfileController.java
> +    @GetMapping("get")
`get`이라는 의미는 이미 `GET` 메소드에 포함되어있기 때문에 생략이 가능해보입니다~

2021-04-16 03:47 UTC, f-lab-dev commented on src/main/java/com/dev/careers/mapper/ProfileMapper.java
> +    int insertProfile(Profile profile);
인터페이스에서 메소드마다 공백을 하나씩 넣어주면 가독성이 향상됩니다~

2021-04-16 03:47 UTC, f-lab-dev commented on src/main/java/com/dev/careers/model/Academic.java
> +@Getter
`setter`를 쓰면 immutable이 깨질 것 같은데 꼭 깰 필요가 있을까요?

2021-04-16 03:47 UTC, f-lab-dev commented on src/main/java/com/dev/careers/service/CuratorService.java
> +            throw new SqlInsertException();
원인도 예외 메세지에 넣어서 던져주면 좋을 것 같습니다~

2021-04-16 03:47 UTC, f-lab-dev commented on src/main/java/com/dev/careers/service/CuratorService.java
>      public void join(Curator curator) throws NoSuchAlgorithmException {
여기서는 checked exception을 던지는 이유가 있으실까요?

2021-04-16 03:47 UTC, f-lab-dev commented on src/main/java/com/dev/careers/service/CuratorService.java
> +        Integer id = memberInfo
이 값은 null이 들어갈 가능성이 없어보이는데 primitive type을 쓰는게 어떨까요?

2021-04-16 03:47 UTC, f-lab-dev commented on src/main/java/com/dev/careers/service/ProfileService.java
> +            log.info("이미 등록되어있는 사용자 프로필");
이렇게 하면 유저 정보가 업데이트될때마다 로그가 찍힐텐데 초당 수천, 수만의 트래픽이 들어오는 환경에서 과도한 로그가 찍힐 가능성이 있지 않을까요?

2021-04-16 03:47 UTC, f-lab-dev commented on src/main/java/com/dev/careers/service/ProfileService.java
> +            }
이쪽은 꽤나 복잡한데 stream 연산을 사용해서 간결하게 줄이는게 가능해보이네요~

2021-04-16 03:47 UTC, f-lab-dev commented on src/main/java/com/dev/careers/service/error/CuratorExceptionHandler.java
> +    public void sqlError(final RuntimeException ex) {
이렇게 하면 예외가 발생했을때 사용자는 어떤 응답을 받게 되나요?

2021-04-16 03:47 UTC, f-lab-dev commented on src/main/java/com/dev/careers/service/session/SessionAuthenticator.java
> +    private final static String SESSIONNAME = "userID";
`SESSION_NAME`으로 지어주는게 어떨까요?

2021-04-16 03:47 UTC, f-lab-dev commented on src/main/resources/mybatis/CuratorMapper.xml
> +    select id, email, password, salt
예약어는 대문자로 적어주시면 가독성이 높아집니다~

2021-04-16 03:47 UTC, f-lab-dev commented on src/test/java/com/dev/careers/controller/CuratorControllerTest.java
> +            .andExpect(request().sessionAttribute("userID", notNullValue()));
이런 세션 키도 상수를 사용하는게 어떨까요?

2021-04-20 15:49 UTC, phantom08266 commented on sql/ddl.sql
> +    primary key (id, name), -- Profile 테이블에서 foreign key로 사용하기 위해 name도 pk설정
프로필 정보를 받아올때 이름도 필요해서 Profile테이블에서 사용하기 위해 외래키를 걸어두었습니다. 
그러면 프로필 정보를 요청 시 Curator테이블과 Profile테이블을 Join해서 처리하는 것이 더 좋을까요?

2021-04-21 14:15 UTC, phantom08266 commented on src/main/java/com/dev/careers/model/Academic.java
> +@Getter
ProfileService에서 DB에서 읽어온 ProfileID를 설정하기위해 Setter를 사용하였습니다.

2021-04-22 01:49 UTC, f-lab-dev commented on src/main/java/com/dev/careers/controller/ProfileController.java
> +    @PutMapping("update")
`update`도 빼도 되지 않을까요? `PUT`은 update의 뜻을 가지고 있습니다~

2021-04-22 15:59 UTC, phantom08266 commented on src/main/java/com/dev/careers/service/CuratorService.java
>      public void join(Curator curator) throws NoSuchAlgorithmException {
해당 부분은 회피가 아닌 전환으로 처리하여 사용자가 예외발생 시 파악이 가능하도록 수정하였습니다.

2021-04-23 06:14 UTC, f-lab-dev commented on src/main/java/com/dev/careers/model/Academic.java
> +@Getter
새로 객체를 생성해서 복사하는 방법과 이렇게 setter를 쓰는 방법, 두가지가 있을 것 같은데 트레이드오프를 한번 고려해보시면 좋겠습니다~

2021-04-23 06:14 UTC, f-lab-dev commented on sql/ddl.sql
> +    primary key (id, name), -- Profile 테이블에서 foreign key로 사용하기 위해 name도 pk설정
네 그게 좋아보입니다~

2021-04-25 12:24 UTC, f-lab-dev approved these changes

2021-04-26 02:54 UTC, f-lab-dev requested changes

2021-04-26 02:54 UTC, f-lab-dev commented on src/main/java/com/dev/careers/service/ProfileService.java
> +                ))
이 부분도 `map` 메소드를 이용하면 `updateCareers.add`를 해줄 필요가 없어집니다

2021-04-29 02:21 UTC, f-lab-dev approved these changes
👍

2021-05-03 13:30 UTC, dnjwm8612 approved these changes

2021-05-09 05:50 UTC, merged